networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    ports:
      - "8080:80"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    ports:
      - "8081:80"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=172.18.0.4 port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC-3 connect_timeout=5"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.4
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/